In [128]:
import pandas as pd
import seaborn as sns

In [129]:
df = pd.read_csv('./bachelorette.csv')

In [130]:
df.head(30)

,SHOW,SEASON,CONTESTANT,ELIMINATION-1,ELIMINATION-2,ELIMINATION-3,ELIMINATION-4,ELIMINATION-5,ELIMINATION-6,ELIMINATION-7,...,DATES-1,DATES-2,DATES-3,DATES-4,DATES-5,DATES-6,DATES-7,DATES-8,DATES-9,DATES-10
0,SHOW,SEASON,ID,1,2,3,4,5,6,7,...,1,2,3,4,5,6,7,8,9,10
1,Bachelorette,13,13_BRYAN_A,R1,NaN,NaN,R,R,NaN,R,...,NaN,NaN,D6,D13,D1,D7,D1,D1,D1,D1
2,Bachelorette,13,13_PETER_K,NaN,R,NaN,NaN,NaN,R,R,...,NaN,D1,D6,D13,D9,D7,D1,D1,D1,D1
3,Bachelorette,13,13_ERIC_B,NaN,NaN,R,NaN,NaN,R,R,...,NaN,D10,D8,D13,D9,D1,D3,D1,D1,NaN
4,Bachelorette,13,13_DEAN_U,NaN,R,NaN,R,NaN,NaN,R,...,NaN,D8,D8,D1,D9,D7,D1,D1,NaN,NaN
5,Bachelorette,13,13_ADAM_G,NaN,NaN,NaN,NaN,NaN,NaN,ED,...,NaN,D10,D8,D13,D9,D7,D3,NaN,NaN,NaN
6,Bachelorette,13,13_MATT_M,NaN,NaN,NaN,NaN,NaN,NaN,ED,...,NaN,D10,NaN,D13,D9,D7,D3,NaN,NaN,NaN
7,Bachelorette,13,13_ALEX_B,NaN,NaN,R,NaN,NaN,E,NaN,...,NaN,D10,D6,D13,D9,D7,NaN,NaN,NaN,NaN
8,Bachelorette,13,13_WILL_G,NaN,NaN,NaN,NaN,R,ED,NaN,...,NaN,D10,D6,D13,D9,D1,NaN,NaN,NaN,NaN
9,Bachelorette,13,13_KENNY_L,NaN,NaN,NaN,NaN,R,ED,NaN,...,NaN,D8,D8,D13,D2,D7,NaN,NaN,NaN,NaN
10,Bachelorette,13,13_ANTHONY_B,NaN,NaN,R,NaN,E,NaN,NaN,...,NaN,NaN,D1,D13,D9,NaN,NaN,NaN,NaN,NaN
11,Bachelorette,13,13_JOSIAH_G,NaN,R,NaN,NaN,E,NaN,NaN,...,NaN,D10,NaN,D13,D9,NaN,NaN,NaN,NaN,NaN
12,Bachelorette,13,13_LEE_G,NaN,NaN,NaN,NaN,ED,NaN,NaN,...,NaN,D10,D8,D13,D2,NaN,NaN,NaN,NaN,NaN
13,Bachelorette,13,13_IGGY_R,NaN,NaN,NaN,E,NaN,NaN,NaN,...,NaN,D8,NaN,D13,NaN,NaN,NaN,NaN,NaN,NaN
14,Bachelorette,13,13_JONATHAN_T,NaN,NaN,NaN,E,NaN,NaN,NaN,...,NaN,D8,D6,D13,NaN,NaN,NaN,NaN,NaN,NaN
15,Bachelorette,13,13_JACK_S,NaN,NaN,NaN,ED,NaN,NaN,NaN,...,NaN,D8,D8,D1,NaN,NaN,NaN,NaN,NaN,NaN
16,Bachelorette,13,13_BRADY_E,NaN,NaN,E,NaN,NaN,NaN,NaN,...,NaN,NaN,D8,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Bachelorette,13,13_BRYCE_P,NaN,NaN,E,NaN,NaN,NaN,NaN,...,NaN,NaN,D8,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Bachelorette,13,13_DIGGY_M,NaN,NaN,E,NaN,NaN,NaN,NaN,...,NaN,D10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Bachelorette,13,13_FRED_J,NaN,NaN,ED,NaN,NaN,NaN,NaN,...,NaN,D8,D6,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Bachelorette,13,13_BLAKE_E,NaN,E,NaN,NaN,NaN,NaN,NaN,...,NaN,D8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Bachelorette,13,13_JAMEY_K,NaN,E,NaN,NaN,NaN,NaN,NaN,...,NaN,D10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Bachelorette,13,13_LUCAS_Y,NaN,E,NaN,NaN,NaN,NaN,NaN,...,NaN,D8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,Bachelorette,13,13_DEMARIO_J,NaN,EU,NaN,NaN,NaN,NaN,NaN,...,NaN,D10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,Bachelorette,13,13_BLAKE_K,E,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,Bachelorette,13,13_GRANT_H,E,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,Bachelorette,13,13_JEDIDIAH_B,E,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Bachelorette,13,13_KYLE_S,E,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Bachelorette,13,13_MICHAEL_B,E,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Bachelorette,13,13_MILTON_L,E,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [178]:
df = df[["CONTESTANT","ELIMINATION-1", "ELIMINATION-10" ]]

In [179]:
firstImpression = df[df["ELIMINATION-1"] == "R1"]

In [180]:
firstImpression

         CONTESTANT ELIMINATION-1 ELIMINATION-10
1        13_BRYAN_A            R1              W
33      12_JORDAN_R            R1              W
60       11_SHAWN_B            R1            NaN
88        10_NICK_V            R1             EU
114       09_DREW_K            R1             ED
116        09_ZAK_W            R1            NaN
117    09_MICHAEL_G            R1            NaN
122        09_BEN_S            R1            NaN
123     09_BRYDEN_V            R1            NaN
129       09_NICK_M            R1            NaN
144       08_DOUG_C            R1            NaN
170       07_RYAN_P            R1            NaN
191     06_ROBERT_M            R1              W
227      05_DAVID_G            R1            NaN
248      04_JESSE_C            R1            NaN
250     04_JEREMY_A            R1            NaN
259    04_RICHARD_M            R1            NaN
281        03_KEITH            R1            NaN
352    21_VANESSA_G            R1              W
390     20_OLIVIA_C            R1            NaN
417      19_BRITT_N            R1            NaN
448   18_SHARLEEN_J            R1            NaN
471  17_CATHERINE_G            R1              W
473     17_ASHLEE_F            R1            NaN
474    17_DESIREE_H            R1            NaN
476     17_TIERRA_L            R1            NaN
478      17_SLEMA_A            R1            NaN
479      17_SARAH_H            R1            NaN
480      17_ROBYN_H            R1            NaN
481     17_JACKIE_[            R1            NaN
483     17_LESLIE_H            R1            NaN
487     17_BROOKE_B            R1            NaN
488      17_DIANA_W            R1            NaN
489      17_LATIE_L            R1            NaN
499     16_LINDZI_C            R1              E
534     15_ASHLEY_S            R1            NaN
556     14_TENLEY_M            R1            NaN
589      13_NIKKI_K            R1            NaN
609     12_AMANDA_R            R1            NaN
634      11_JENNI_C            R1            NaN
667  10_STEPHANIE_T            R1            NaN
687       09_LISA_B            R1            NaN
741     07_Sarah W.            R1            NaN
747        07_Kerry            R1            NaN
796      05_TRISH_S            R1            NaN

In [181]:
firstImpression = firstImpression[firstImpression["ELIMINATION-10"] == "W"]

In [182]:
firstImpression

         CONTESTANT ELIMINATION-1 ELIMINATION-10
1        13_BRYAN_A            R1              W
33      12_JORDAN_R            R1              W
191     06_ROBERT_M            R1              W
352    21_VANESSA_G            R1              W
471  17_CATHERINE_G            R1              W